myV2MOM/objects/Measure__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completion_By_Date__c</fullName>
        <label>Completion By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Completion_By_Quarter__c</fullName>
        <label>Completion By Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
                <value>
                    <fullName>Q4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Method</label>
        <referenceTo>Method__c</referenceTo>
        <relationshipLabel>Measures</relationshipLabel>
        <relationshipName>Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obstacles__c</fullName>
        <label>Obstacles</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Q1_Target__c</fullName>
        <label>Q1 Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q1__c</fullName>
        <label>Q1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q2_Target__c</fullName>
        <label>Q2 Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q2__c</fullName>
        <label>Q2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q3_Target__c</fullName>
        <label>Q3 Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q3__c</fullName>
        <label>Q3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q4_Target__c</fullName>
        <label>Q4 Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q4__c</fullName>
        <label>Q4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Split_By_Quarter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split By Quarter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Track</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Behind Schedule</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Value__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Progress_By__c</fullName>
        <label>Track Progress By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completion Status</fullName>
                </value>
                <value>
                    <fullName>Numbers Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Measure</label>
    <language>en_US</language>
    <nameField>
        <label>Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/myV2MOM/objects/Method__c.object
<CustomObject>
    <label>Method</label>
    <nameField>
        <label>Methods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Methods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/myV2MOM/classes/V2MOM_Measure_Controller.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class V2MOM_Measure_Controller {
    
    @AuraEnabled
    //Method to return current quarter end date
    public static date getQuarterEndDate(Integer currentQuarter){
        try{
            return V2MOM_UtilCls.getFiscalQuarterEndDate(currentQuarter);
        }catch(exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @auraEnabled
    //Method to create a Measure
    public static void createMeasure(Measure__c measure){
        if(measure.Priority__c == 'H'){
            measure.Priority__c = 'High';
        }else if(measure.Priority__c == 'M'){
            measure.Priority__c = 'Medium';
        }else if(measure.Priority__c == 'L'){
            measure.Priority__c = 'Low';
        }
        
        if(measure.Track_Progress_By__c == 'N'){
            measure.Track_Progress_By__c = 'Numbers Completed';
        }else if(measure.Track_Progress_By__c == 'C'){
            measure.Track_Progress_By__c = 'Completion Status';
        }
        List<String> measFields = MeasureChatterCtrlSharing.getMeasureFields();
        if(FLSCheck.isAccessible(measFields,'Measure__c') && FLSCheck.isCreateable(measFields,'Measure__c') && FLSCheck.isUpdateable(measFields,'Measure__c')){
            upsert measure; 
        }
        
    }
    
    //---------------- For Mobile ----------------
    @AuraEnabled
    //Set picklist values on the lightning component
    public static Map<String, List<V2MOM_UtilCls.labelValueWrap>> getAllMeasurePickLists(){
        Map<String, List<V2MOM_UtilCls.labelValueWrap>> pickMap = new Map<String, List<V2MOM_UtilCls.labelValueWrap>>();
        pickMap.put('progress', getProgressTypesMobile());
        pickMap.put('priority', getPriorityTypesMobile());
        pickMap.put('status', getStatusTypesMobile());
        return pickMap;
    }
    
    @AuraEnabled
    //get all available progress type values
    public static List<V2MOM_UtilCls.labelValueWrap> getProgressTypesMobile(){
        List<V2MOM_UtilCls.labelValueWrap> options = new List<V2MOM_UtilCls.labelValueWrap>();
        if(FLSCheck.isAccessible(MeasureChatterCtrlSharing.getMeasureFields(),'Measure__c')){
            Schema.DescribeFieldResult fieldResult = Measure__c.Track_Progress_By__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry f: ple) {
                options.add(new V2MOM_UtilCls.labelValueWrap(f.getLabel(), f.getValue()));
            }
        }
        return options;
    }
    @AuraEnabled
    //Method to return available priority types from Priority__c field on Measure__c object
    public static List<V2MOM_UtilCls.labelValueWrap> getPriorityTypesMobile(){
        List<V2MOM_UtilCls.labelValueWrap> options = new List<V2MOM_UtilCls.labelValueWrap>();
        if(FLSCheck.isAccessible(MeasureChatterCtrlSharing.getMeasureFields(),'Measure__c')){
            Schema.DescribeFieldResult fieldResult = Measure__c.Priority__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry f: ple) {
                options.add(new V2MOM_UtilCls.labelValueWrap(f.getLabel(), f.getValue()));
            }
        }
        return options;
    }
    
    @AuraEnabled
    //Method to return available status types from Status__c field on Measure__c object
    public static List<V2MOM_UtilCls.labelValueWrap> getStatusTypesMobile(){
        List<V2MOM_UtilCls.labelValueWrap> options = new List<V2MOM_UtilCls.labelValueWrap>();
        if(FLSCheck.isAccessible(MeasureChatterCtrlSharing.getMeasureFields(),'Measure__c')){
            Schema.DescribeFieldResult fieldResult = Measure__c.Status__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry f: ple) {
                options.add(new V2MOM_UtilCls.labelValueWrap(f.getLabel(), f.getValue()));
            }
        }
        return options;
    }
    //---------------- For Mobile ----------------
    
    @AuraEnabled
    //get all available progress type values
    public static List<String> getProgressTypes(){
        List<String> options = new List<String>();
        if(FLSCheck.isAccessible(MeasureChatterCtrlSharing.getMeasureFields(),'Measure__c')){
            Schema.DescribeFieldResult fieldResult = Measure__c.Track_Progress_By__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry f: ple) {
                options.add(f.getLabel());
            }
        }
        return options;
    }
    @AuraEnabled
    //Method to return available priority types from Priority__c field on Measure__c object
    public static List<String> getPriorityTypes(){
        List<String> options = new List<String>();
        if(FLSCheck.isAccessible(MeasureChatterCtrlSharing.getMeasureFields(),'Measure__c')){
            Schema.DescribeFieldResult fieldResult = Measure__c.Priority__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry f: ple) {
                options.add(f.getLabel());
            }
        }
        return options;
    }
    
    @AuraEnabled
    //Method to return available status types from Priority__c field on Measure__c object
    public static List<String> getStatusTypes(){
        List<String> options = new List<String>();
        if(FLSCheck.isAccessible(MeasureChatterCtrlSharing.getMeasureFields(),'Measure__c')){
            Schema.DescribeFieldResult fieldResult = Measure__c.Status__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry f: ple) {
                options.add(f.getLabel());
            }
        }
        return options;
    }
    @AuraEnabled
    //Method to return available details on a measure based on the measure id passed
    public static Measure__c getMeasureDetails(String measId){
        List<String> measFields = MeasureChatterCtrlSharing.getMeasureFields();
        if(!FLSCheck.isAccessible(measFields,'Measure__c')){
            Measure__c measure = new Measure__c();
            return measure;
        }
        Measure__c meas = [SELECT Id, Name, Track_Progress_By__c, Priority__c, Status__c, Method__c, Target_Value__c, Current_Value__c, Split_By_Quarter__c, Completion_By_Date__c, Completion_By_Quarter__c, Q1__c, Q2__c, Q3__c, Q4__c, Q1_Target__c, Q2_Target__c, Q3_Target__c, Q4_Target__c, Comments__c, Obstacles__c FROM Measure__c WHERE Id =: measId];
        return meas;
    }
    
}